package cn.maian.rescue.domain;

public enum RescueEventType {
    CREATED,
    MATCHING_STARTED,
    AED_ASSIGNED,
    ACCEPTED,
    ARRIVED_AT_AED,
    AED_PICKED_UP,
    ARRIVED_AT_REQUESTER,
    RESCUE_STARTED,
    COMPLETION_SUBMITTED,
    COMPLETION_CONFIRMED,
    COMPLETION_AUTO_CONFIRMED,
    AED_RETURNED,
    USER_CANCELLED,
    NO_RESOURCE,
    EXPIRED,
    SYSTEM_FAILED
}
